# fly.toml app configuration file generated for foodies-app on 2024-05-24T00:55:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foodies-app'
primary_region = 'otp'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
